Add support for implementation factory in builder extensions
gsoft-inc/gsoft-cqrs pull request #2
Opened 2022-08-22 17:06 UTC by Yalpe

2022-08-22 20:39 UTC, code-person approved these changes

2022-08-23 13:53 UTC, decarufe requested changes

2022-08-23 13:53 UTC, decarufe commented on src/GSoft.Cqrs/Configuration/DependencyInjection/BuilderExtensions/CqrsBuilderExtensions.cs
> +    public static void AddHandler<THandler>(this IServiceCollection services, Func<IServiceProvider, object> implementationFactory, ServiceLifetime serviceLifetime = ServiceLifetime.Transient)
_implementationFactory_ should be of type _THandler_
 so the second parameter should be 
_Func<IServiceProvider, THandler> implementationFactory_

2022-08-23 13:53 UTC, decarufe commented on src/GSoft.Cqrs/Configuration/DependencyInjection/BuilderExtensions/CqrsBuilderExtensions.cs
> +    public static void AddHandler<THandler, TEvent>(this IServiceCollection services, Func<IServiceProvider, object> implementationFactory, ServiceLifetime serviceLifetime = ServiceLifetime.Transient
_implementationFactory_ should be of type _THandler_
 so the second parameter should be 
_Func<IServiceProvider, THandler> implementationFactory_

2022-08-23 18:09 UTC, decarufe approved these changes

2022-08-23 18:10 UTC, decarufe approved these changes

2022-08-23 19:51 UTC, merged