feat(fix): discard abstract handlers in auto-registration
gsoft-inc/gsoft-cqrs pull request #6
Opened 2022-08-31 20:49 UTC by felpel

Ensure abstract handlers are discarded in the auto-registration process, since they can't be instantiated unless they are inherited from any concrete types

2022-08-31 22:43 UTC, decarufe requested changes

2022-08-31 22:43 UTC, decarufe commented on src/GSoft.Cqrs/Configuration/DependencyInjection/BuilderExtensions/CqrsBuilderExtensions.cs
> +            where !type.IsAbstract
J'aurais mis le abstract filter avant le typeFilter. Si le type filter est implémenté par une méthode plus complexe, on ne veut pas avoir a gérer les abstract qui seront de toute façon retiré par la suite.

2022-09-01 12:57 UTC, decarufe approved these changes

2022-09-01 13:45 UTC, lballaire commented on src/GSoft.Cqrs.Tests/CqrsBuilderExtensionsTests.cs
> +    private record GetChildressQuery : IQuery<string>;
Typo : Childless

2022-09-01 13:48 UTC, lballaire requested changes
Just a small typo that should be fixed, otherwise LGTM

2022-09-01 14:55 UTC, felpel commented on src/GSoft.Cqrs.Tests/CqrsBuilderExtensionsTests.cs
> +    private record GetChildressQuery : IQuery<string>;
# 🤦 

C'est réglé ✅

2022-09-01 15:00 UTC, lballaire approved these changes

2022-09-01 15:00 UTC, merged